@keycloak_server = http://localhost:8888 
@admin_token = eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaTE5hVndvcS1XM3BfLVJVbjhybXpmVVZxNFJsNTdlMTNEemJ3dDM4ZTFBIn0.eyJleHAiOjE3MDIyMTY2MTUsImlhdCI6MTcwMjIxNjMxNSwianRpIjoiMGNmM2ZkZGUtMTE3ZS00NGFmLWEzOTQtNmExMGZmMjQ0MWI2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4L3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI5ODQ5YmVmNC05M2U2LTQ3MDAtYmU0NC05MDcxZjM0OGQxNDgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiNGRlODZiZTUtY2E3OS00NDNjLWE3ZGUtNDk5NWI5YjVkODVhIiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjRkZTg2YmU1LWNhNzktNDQzYy1hN2RlLTQ5OTViOWI1ZDg1YSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.ZSWL2A_xDhZrIISbGghEi_epuCTFLa1fZFrwVfn6PU0DgJG-TvvreE-3KK9GhuQLuqqoGFVoAKy5j72QpJdr51Qtij4uj1lgj9jxQ6Oo_TRKIm9OQLQqgm6uEKZ6bci9l3AanVjaMD5lM_XkfhtQ2enOprXtW8GNmcngQZBppzlG9iKNcRbI-mKkT0mdl0SJuDMGVXbOxM07ey4PnIAueXkPrAJUOe5cc0g_sA9uYQhx1QwslohFjq6nwUBpq6g8uAS4QaxZNs-FRqt5167FuVLXEVixLXxjGA7Sogm4sKq9YpobH6vKq0m1zrOHTsL3ywPnzif7eel32rQK8ahx7A

# Get User Token
GET {{keycloak_server}}/admin/realms/F1Fantasy/roles/regular-user
Authorization: Bearer {{admin_token}}
