@keycloak_server = http://localhost:8888 

# Create User
POST {{keycloak_server}}/admin/realms/F1Fantasy/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaTE5hVndvcS1XM3BfLVJVbjhybXpmVVZxNFJsNTdlMTNEemJ3dDM4ZTFBIn0.eyJleHAiOjE3MDE4MjQyODksImlhdCI6MTcwMTgyMzk4OSwianRpIjoiMmYyMDAxOTUtNWJhNy00Mjk1LTgxNGMtMjE5MmY2MzM4NzNkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4L3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI5ODQ5YmVmNC05M2U2LTQ3MDAtYmU0NC05MDcxZjM0OGQxNDgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiZTJmOTQwMjMtMjVhZC00NDczLWIzOWItNDhkNDRmN2Q1ODkyIiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImUyZjk0MDIzLTI1YWQtNDQ3My1iMzliLTQ4ZDQ0ZjdkNTg5MiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.MIHuBq4cAcVFfxqLj3EPDNaEPYI9GhLkfvSXSNfFpN4bBhUp388wEAszgmEiV3C4mxBtOW0ZnY3ssVZ3AZelursQ4zf0PoHU6H14Td6sdkRmMoC0eCNKloxbM3x580jJiE6T7h5AwboNPCyMBEr8u48N1jKFP9tVgpCX3okF_QpLbVxPvvMJrLPcatRIKxZtPmdLywL8VgTKOl7NoEtjwiLcFvd4P5fc1YLqqhXRQgb0hVsCms7_WDCltF5YZoNZsvQpn_waGnMkmoslvGeNlnmmEbJDlUYc9fO84kXG-6WVmm_ta9EOnmUoqSBeTWa0NM5re081LhjbMtkxcbJP1A
Content-Type: application/json

{ 
    "username":"john.doe-test.com",
    "firstName":"John",
    "lastName":"Doe", 
    "email":"john.doe@test.com", 
    "enabled":"true", 
    "attributes": [

    ],
    "roles": [

    ]
    "credentials": [
        {
            "type": "password",
            "value": "123456",
            "temporary": false
        }
    ]
}