@keycloak_server = http://localhost:8888 

# Create API Client
POST {{keycloak_server}}/admin/realms/F1Fantasy/clients
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaTE5hVndvcS1XM3BfLVJVbjhybXpmVVZxNFJsNTdlMTNEemJ3dDM4ZTFBIn0.eyJleHAiOjE3MDIxNDc1MjgsImlhdCI6MTcwMjE0NzIyOCwianRpIjoiMzZhZjNmN2QtYTYxNC00MDg4LTkxNTQtYjY0NDM1NjlkOWQwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4L3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI5ODQ5YmVmNC05M2U2LTQ3MDAtYmU0NC05MDcxZjM0OGQxNDgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiYTM5ZmEzODEtYjkyMy00YjZhLWFjNTMtYWMzODJiZWM0ZDY4IiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImEzOWZhMzgxLWI5MjMtNGI2YS1hYzUzLWFjMzgyYmVjNGQ2OCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.MwOvjD5cLq62X4lxSqk4ucThwbvD4guix7pR6XxxICj3mSesd52uzZvMx1u-Tz9RZyK7MMsB6qOUQao2mBUAUGywxrkX_45_TqJaM6pC3WHeqK3YLGT_EhZ9Nqyyoq8OdDu4vMqgDzlf5qgkt89Tv4U-g-WB9MG6gaY5CAqwsdF8DFRCkB_Dd-zMiBKdd05q5Up-WBZk-iMnO7pAknMO_Y705ExxbMXPgaFziqJjUL9YNNb0sLz8OZ4UW7CgYU-vzIwXNoye73DkS4SDqcjSvBnGNEEqab118XaKERMsEQ_-n0PysSzkcfUV-MZ0NYv1fbr7emndq6OCQGKf7dqySQ
Content-Type: application/json

{ 
    "clientId":"api-simulation",
    "name":"api-simulation",
    "publicClient": true,
    "directAccessGrantsEnabled": true,
    "fullScopeAllowed": false
}