@keycloak_server = http://localhost:8888 
@username = john.doe-test.com
@password = 123456

# Get User Token
POST {{keycloak_server}}/realms/F1Fantasy/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=web-frontend&username={{username}}&password={{password}}
