@keycloak_server = http://localhost:8888 
@admin_token = eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaTE5hVndvcS1XM3BfLVJVbjhybXpmVVZxNFJsNTdlMTNEemJ3dDM4ZTFBIn0.eyJleHAiOjE3MDIyMTkwODEsImlhdCI6MTcwMjIxODc4MSwianRpIjoiNTFiZWQzNTctYmZjNy00ZmRiLTk5MDUtODBlMzViMzNiNWYwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4L3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI5ODQ5YmVmNC05M2U2LTQ3MDAtYmU0NC05MDcxZjM0OGQxNDgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiZTA3MjlkNTAtOWUwZS00YjcwLTkzNzUtYThlOGQ5ZjI3ODFlIiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImUwNzI5ZDUwLTllMGUtNGI3MC05Mzc1LWE4ZThkOWYyNzgxZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.awwIwMTnFxmwYkd0Pn6xbhFthqKImtMiCbKKr3qfvktSkwoyI2PQGcUZKSgZ9tC9eeLAZVvJCshK_YG0QJUeNAbsc-AY-q_X7Hlt-k4tA3tj_1hxsc57kvc6AAjnjuN5lZZny2dyVRW2Y4BBvoXpWh2ayUVqYmo9iH-hVAumo_bu9r5JnzXYb7NxUjSQ65G-8GRLlEc9INBXNB6zP2vRn7_cHzwrld0PsaQoAaW-bvbmpExV2AshmB0dqsMJyg4FWDj8xzKpAufFPTFaS_IGLUf2kWSQg4X5qUTm1OL5kJToLWhkI0249SgUGJNwc9X-MRuJRl_s7zt5yQna05cOow
# Returned from "Create Frontend Client" request
@cliend-internal-id = a03c19b1-5f9f-4e9e-8ef9-c62ebf136294

# Create API Client
POST {{keycloak_server}}/admin/realms/F1Fantasy/clients/{{cliend-internal-id}}/protocol-mappers/models
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
    "name":"audience-mapper",
    "protocol":"openid-connect",
    "protocolMapper":"oidc-audience-mapper",
    "config":{
        "included.client.audience":"api-simulation",
        "access.token.claim":"true"
    }
}