@keycloak_server = http://localhost:8888 

# Create API Client
POST {{keycloak_server}}/admin/realms/F1Fantasy/clients
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaTE5hVndvcS1XM3BfLVJVbjhybXpmVVZxNFJsNTdlMTNEemJ3dDM4ZTFBIn0.eyJleHAiOjE3MDE4MjUwMzksImlhdCI6MTcwMTgyNDczOSwianRpIjoiZjE5YmE2MGItZDk5MS00Nzc1LTg3NzAtNWQ2MjQzYzUxMjUyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4L3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI5ODQ5YmVmNC05M2U2LTQ3MDAtYmU0NC05MDcxZjM0OGQxNDgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiZWI0YTFkY2UtMTZjMS00NDMxLTlkZjUtOThjMzVjZTYyYTViIiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImViNGExZGNlLTE2YzEtNDQzMS05ZGY1LTk4YzM1Y2U2MmE1YiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.Honruc9bvbGPfm8NfTrEIen9IKT0wUEfbpr70gQh7c2_Xgxj5PuUjvz2k2GWwD7nqRbEHmGZziuLKL1lu3xzMOFNQ6OmaFOVVRg8IENA23dJxse1HuadtDWiNHS-teMTgMzmSuO_cmh2pYP6-4ijmEXFK730MC5vF5sDFp3uM226AA9OIsQ--gLIVbraSzs6TC20dgUx9-LIm_KZFIiaspeEf4C7Fu696BOavfdkLYaQeEFlyWg-lBqPhD7alZH94GIcKMs6qke7s-BKf8skddmLd1a9NXc_UWbyvctxTIsYoe169n0WVkEcOK_1Z9D1ImV_0uIlM2RXJpLkxufA4A
Content-Type: application/json

{ 
    "clientId":"api-simulation",
    "name":"api-simulation"
}