@keycloak_server = http://localhost:8888 
@admin_token = eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaTE5hVndvcS1XM3BfLVJVbjhybXpmVVZxNFJsNTdlMTNEemJ3dDM4ZTFBIn0.eyJleHAiOjE3MDIyMTYxMTUsImlhdCI6MTcwMjIxNTgxNSwianRpIjoiNDM3M2FlYWUtOTQ3ZC00NmM0LTkzYzMtMWNkZjFlZjRjYjIwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4L3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI5ODQ5YmVmNC05M2U2LTQ3MDAtYmU0NC05MDcxZjM0OGQxNDgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiOTA0NThkNWEtMzgzYi00MTQ1LTk1NjQtMjhhZGVmMDU4ZGM5IiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjkwNDU4ZDVhLTM4M2ItNDE0NS05NTY0LTI4YWRlZjA1OGRjOSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.VnEEwRObx4dOEHvUbvNRqMTcvaPq51N3KW1BGz52VXByjY92Jr29_YXV4ylhbIIHEHbHjNXk8L_aXlqUhnu-DDkUC4GENuVBpjapyly8O9vDJW4_bDC0VdOZi53KPiGyX2phSykjkWFGOplQd5jRjLWmqiPinfcJEIYFlNc8U3GdjHkmuVUEr0wyPysSfrvyV92IRnLc0FEMf82z9tFaWthUr3yWBdCDEiaeHpXcpw_rGiPwLw4TW4rvwYVj0-j___AMOFFNAlQlrywEv3VbK0yqWwMmD9zjIIAM5efn5eBX_UYwo-c43iU51ujC6Tj7b8oTmfL5hZWPtklbVbF6gA

# Create API Client
POST {{keycloak_server}}/admin/realms/F1Fantasy/clients
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{ 
    "clientId":"api-simulation",
    "name":"api-simulation",
    "clientAuthenticatorType": "client-secret",
    "publicClient": false,
    "directAccessGrantsEnabled": false,
    "fullScopeAllowed": false
}