version: '3.4'

services:
  f1fantasy.simulation.api:
    image: ${DOCKER_REGISTRY-}f1fantasy.simulation.api
    build:
      context: .
      dockerfile: Simulation/Presentation/F1Fantasy.Simulation.Api/Dockerfile

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    ports:
      - 8888:8080
    command: ['start-dev']
  
volumes:
  keycloak-data: